### ISSUE TITLE
Parsing ContentType is too restrictive

### ISSUE THREAD

**Issue by dtabakov** [linked-data-dotnet/json-ld.net#12]
DocumentLoader::LoadDocument() tries to validate that the media type is JSON-LD. However, the check is too strict: it only passes if the content type is equal to "application/ld+json". This excludes other valid strings like "application/ld+json; charset=utf-8". Specifying the charset is very common for users who create their response messages using System.Net.Http.dll (e.g., using StringContent).

An easy fix is to replace equality check with "StartsWith()".

**Comment by goofballLogic** [comment]
Reconsidering as part of #60

**Comment by goofballLogic** [comment]
Should be implemented in conjunction with #21
