### ISSUE TITLE
Version 1.0.7 is missing on nuget.org

### ISSUE THREAD

**Issue by andrewyakonyuk** [linked-data-dotnet/json-ld.net#121]
Hi,

I want to use  json-ld.net in my project on .net 3.0 however I cannot find the correct version.
On the [nuget.org/json-ld.net](https://www.nuget.org/packages/json-ld.net/) the most recent version is 1.0.6.
This version have dependencies on release candidates (e.g. NETStandard.Library (>= 1.5.0-rc2-24027) which I do not want to use.
However, I found package version 1.0.7 on [github](https://github.com/linked-data-dotnet/json-ld.net/packages/424184?version=1.0.7).

Is there any reason it hasn't been published on nuget.org?

Thanks.

**Comment by asbjornu** [comment]
I actually don't quite understand how version 1.0.7 was published, since we have no tag created for it. It looks like we probably should create a 1.0.7 release for 8c0934bf07aee05bf921016cf409365b9692e6da. Thoughts @goofballLogic?

**Comment by goofballLogic** [comment]
I'm not sure @asbjornu we should probably shift the publishing to a pipeline process to avoid this.

**Comment by asbjornu** [comment]
@goofballLogic, I think most things are in place to publish a `.nupkg` to nuget.org when we push a `git tag`: 

https://github.com/linked-data-dotnet/json-ld.net/blob/80273e10198ba70eae85271adc31725445b62b60/.github/workflows/dotnet.yml#L96-L113

However, I'm unsure whether 8c0934bf07aee05bf921016cf409365b9692e6da (`HEAD` of `support/1.x`) is in working order or not. Do you know?

**Comment by goofballLogic** [comment]
nope. Haven't touched it in over a year. I understood there was a parallel effort underway to significantly refactor the library?





---- On Thu, 04 Nov 2021 20:28:13 +0000 Asbjørn Ulsberg ***@***.***> wrote ----




https://github.com/goofballLogic, I think most things are in place to publish a .nupkg to nuget.org when we push a git tag:

https://github.com/linked-data-dotnet/json-ld.net/blob/80273e10198ba70eae85271adc31725445b62b60/.github/workflows/dotnet.yml#L96-L113

However, I'm unsure whether https://github.com/linked-data-dotnet/json-ld.net/commit/8c0934bf07aee05bf921016cf409365b9692e6da (HEAD of support/1.x) is in working order or not. Do you know?

**Comment by asbjornu** [comment]
> nope. Haven't touched it in over a year.

Ok, same.

> I understood there was a parallel effort underway to significantly refactor the library?

Yeah, that's ongoing in the `main` branch. Could you please take `support/1.x` for a spin, @andrewyakonyuk? If you give it thumbs up, I'll whip out a `1.0.7` release from it.

**Comment by asbjornu** [comment]
I'm happy to inform you that [json-ld.net version 1.0.7 is published on NuGet](https://www.nuget.org/packages/json-ld.net/1.0.7). Please give it for a spin!
