### ISSUE TITLE
Update NETStandard dependencies to stable versions

### ISSUE THREAD

**Issue by emgarten** [linked-data-dotnet/json-ld.net#18]
json-ld.net currently uses pre-release dependencies for NETStandard. Now that stable versions are available the project should be updated to use the latest stable packages.

https://github.com/NuGet/json-ld.net/blob/353e89eafdba1bee481925ee710d2407a24c641a/src/json-ld.net/project.json#L39-L42

The project should also be updated to csproj instead of xproj.

**Comment by goofballLogic** [comment]
Reopening as part of #59
