### ISSUE TITLE
No remote context on CoreCLR ?

### ISSUE THREAD

**Issue by goofballLogic** [linked-data-dotnet/json-ld.net#21]
A seemingly simple operation of retrieving a remote context document appears not to be supported on .NET Core for some reason????

From https://github.com/NuGet/json-ld.net/blob/master/src/json-ld.net/Core/DocumentLoader.cs#L15
```
namespace JsonLD.Core
{
    public class DocumentLoader
    {
        /// <exception cref="JsonLDNet.Core.JsonLdError"></exception>
        public virtual RemoteDocument LoadDocument(string url)
        {
#if !PORTABLE && !IS_CORECLR
            . . . snipped . . .
            return doc;
#else
            throw new PlatformNotSupportedException();
#endif
        }
```

Is this code being used in anger?

**Comment by goofballLogic** [comment]
I have a patch for this which I can submit as a PR if you're open to it. We need it in our codebase and I'd rather be referencing the nuget version than a private fork.

**Comment by CBielstein** [comment]
Just ran in to the same issue when trying out json-ld.net from netcore2.2. I would love to see this PR happen. Let me know if I can help out at all.

**Comment by goofballLogic** [comment]
I'm not aware of anyone currently tackling this issue. If you wish to propose a PR, it would be most welcome.





---- On Tue, 19 Feb 2019 22:15:08 +0000 Cameron Bielstein <mailto:notifications@github.com> wrote ----




Just ran in to the same issue when trying out json-ld.net from netcore2.2. I would love to see this PR happen. Let me know if I can help out at all.

**Comment by CBielstein** [comment]
I'll add it to my todo list, take a swing at it when I have time, and report back.

**Comment by goofballLogic** [comment]
Reopening for consideration as part of #60

**Comment by asbjornu** [comment]
Ideas for a label we can give these issues to exempt from stalebot, @goofballLogic?

**Comment by goofballLogic** [comment]
"planed" ?

**Comment by asbjornu** [comment]
If so, perhaps we can just use milestones? Stalebot can exempt issues associated with milestones as well. If we have an idea of a version number, let's use that as milestone name, otherwise we can just use `future`, `next` or something similar?
