### ISSUE TITLE
Stewardship of Nuget package

### ISSUE THREAD

**Issue by goofballLogic** [linked-data-dotnet/json-ld.net#27]
I have set up https://www.nuget.org/profiles/linked-data-dotnet as a (temporary?) organisation to host the Nuget package. To be secure it's best if at least 2 people have administrative oversight of this organisation (and are able to publish new versions etc.)

@asbjornu do you have a Nuget username and would you be willing to be added to the Nuget organisation and associated google group (email list)?

**Comment by asbjornu** [comment]
Yes, I'm [asbjornu](https://www.nuget.org/profiles/asbjornu) pretty universally. :)

**Comment by veikkoeeva** [comment]
Should this be closed now? :)
