### ISSUE TITLE
Support JSON-LD 1.1

### ISSUE THREAD

**Issue by goofballLogic** [linked-data-dotnet/json-ld.net#28]
As suggested by @veikkoeeva the library needs updated to support 1.1

**Comment by tmarkovski** [comment]
Are there any plans to add this? We'd be happy to invest resources. Is the team looking for contributions in this repo?

**Comment by asbjornu** [comment]
We warmly welcome contributions, @tmarkovski! 🙏 The only requirement I have is that the provided code is well tested against the [JSON-LD test suite](https://json-ld.org/test-suite/).
