### ISSUE TITLE
JsonLdProcessor.Frame(...):  poor performance on large sets of objects

### ISSUE THREAD

**Issue by dtivel** [linked-data-dotnet/json-ld.net#31]
Version 1.0.4

From http://www.w3.org/TR/json-ld-api/#node-map-generation:

> 6.6.6.2) Otherwise, compare reference against every item in the array associated with the active property member of node. If there is no item equivalent to reference, append reference to the array. Two JSON objects are considered equal if they have equivalent key-value pairs.

This is implemented in json-ld.net as an _n_-squared algorithm, where _n_ is the number of elements in the set.  `JsonLdProcessor.Frame(...)` calls `JsonLdApi.GenerateNodeMap(…)`, which [for each element in an array](https://github.com/linked-data-dotnet/json-ld.net/blob/258473e969188f83c668f10f43542180e46ab5ce/src/json-ld.net/Core/JsonLdApi.cs#L1082) [calls `JsonLdUtils.MergeValue(…)`](https://github.com/linked-data-dotnet/json-ld.net/blob/258473e969188f83c668f10f43542180e46ab5ce/src/json-ld.net/Core/JsonLdApi.cs#L1207), which in turn calls [`JsonLdUtils.DeepCompare(…)`](https://github.com/linked-data-dotnet/json-ld.net/blob/258473e969188f83c668f10f43542180e46ab5ce/src/json-ld.net/Core/JsonLdUtils.cs#L139) on the current set.

**Comment by dtivel** [comment]
Repro:  build and run this project:  [JsonLdRepro.zip](https://github.com/linked-data-dotnet/json-ld.net/files/2161402/JsonLdRepro.zip)

**Comment by goofballLogic** [comment]
This should be considered in connection with #60
