### ISSUE TITLE
Strong name sign json-ld.net assemblies

### ISSUE THREAD

**Issue by dtivel** [linked-data-dotnet/json-ld.net#36]
...preferably with [enhanced strong naming](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/enhanced-strong-naming).

**Comment by goofballLogic** [comment]
How do we best handle this in an open-source environment? Open to suggestions

**Comment by loic-sharma** [comment]
An option would be to join the .NET Foundation as they provided code signing services to open source projects. See: https://dotnetfoundation.org/about

**Comment by goofballLogic** [comment]
Any thoughts on .Net Foundation idea @asbjornu ? Do you know if other members of the json-ld wg would have any issues with membership?

**Comment by pietercolpaert** [comment]
A bit related to the .NET foundation: would it make sense to make sure there is a standard RDF representation among .NET RDF projects? There is already an RDFJS standard that can be used as an example: http://rdf.js.org/

**Comment by asbjornu** [comment]
I’m not opposed to .NET Foundation, but I am to strong naming. Perhaps the rationale and experience is different with .NET Core, but back in the framework days, strong naming causes nothing but trouble, with very few real benefits.

If you need a strong name for an assembly, you can strong name it yourself with [Strong Namer](https://github.com/dsplaisted/strongnamer).
