### ISSUE TITLE
Replace Travis with GitHub Actions

### ISSUE THREAD

**Issue by asbjornu** [linked-data-dotnet/json-ld.net#50]
While there are are [many reasons to move away from Travis](https://twitter.com/asbjornu/status/1098873841273708544), the most important one is that Travis has stopped notifying GitHub (see travis-ci/travis-ci#10204). Instead of fixing the Travis checks, I think it's better to just replace it altogether with GitHub Actions.

The rationale to use GitHub Actions is that we're dependent on GitHub for hosting of the source code anyway and GitHub Actions is considered by many (myself included) to be simpler, more feature-rich and more enjoyable than just about every existing alternative.

**Comment by goofballLogic** [comment]
The Travis organisation appears to be having major difficulties and key members of staff are being laid off. There are no indications that the free project will continue to be supported. I second this decision.
