### ISSUE TITLE
Add LINQPad NuGet samples

### ISSUE THREAD

**Issue by sblom** [linked-data-dotnet/json-ld.net#79]
Looks like we've resolved the long-standing "please provide usage examples" request by making the README much better, but I have been intending for ages to add [LINQPad samples to the NuGet package](https://www.linqpad.net/nugetsamples.aspx) so that a developer that wants to kick the tires can simply add the NuGet package to a LINQPad query and start playing around.

Any objections before I roll up my sleeves on that project?

**Comment by asbjornu** [comment]
I don't use LINQPad myself, so I don't really have any basis to judge this upon. But more documentation can't hurt, so I give it a 👍!

**Comment by goofballLogic** [comment]
yeah note that there's also now https://github.com/linked-data-dotnet/json-ld.net-Demo which helps somewhat
